version: "3.3"
services:
  master:
    container_name: jenkins
    image: jenkins:latest
    ports:
      - 18080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    links:
       - jenkins-slave


#  jenkins-slave:
#    container_name: jenkins-slave
#    image: jenkinsci/ssh-slave
#    environment: 
#      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa