version: '3.3'
services: 
    db:
        image: mysql
    web:
        build: . #Dockerfileからimageを適用する
        command: python3 manage.py runserver 0.0.0.0:8080
        volumes: 
            - .:/src
        ports:
            - "8000:8000"
        depends_on:
            - db